name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    IMAGE_TAG: ${{github.run_number}}
    DOCKER_REPOSITORY: order256
    IMAGE_NAME: webapp

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./app-dotnet --file ./app-dotnet/Dockerfile --tag webapp:$IMAGE_TAG

    - name: Tag the Docker image
      run: docker tag $DOCKER_REPOSITORY/webapp:$IMAGE_TAG

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin

    - name: Push Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
